ActionModule DEFINITIONS ::= BEGIN
    IMPORTS Number, Version, Hash 
    FROM BasicModule
    Account 
    FROM AccountModule;

Action ::= SEQUENCE {
    version         Version,
    id              Hash,
    date            UTCTime,
    contract        Hash,
    sourceAccount   Hash,
    targetAccount   Hash,
    value           Number,
    parent          Hash,
    model           ANY
}

END