BlockChainModule DEFINITIONS ::= BEGIN
    IMPORTS Number, Hash, Version, Key
        FROM BasicModule
        Account 
        FROM AccountModule
        Action
        FROM ActionModule
        Transaction, SignedTransaction
        FROM TransactionModule;


Block ::= SEQUENCE {
    version         Version,
    id              Hash,
    date            UTCTime,
    parent          Hash,
    transactions    SEQUENCE OF SignedTransaction,
    merkelRoot      Hash
}

SignedBlock ::= SEQUENCE {
    version         Version,
    id              Hash,
    block           Block,
    hash            Hash,
    signature       Key
}

END
