TransactionModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN
    IMPORTS Number, Hash, Version, Key, Signature
        FROM BasicModule
        Account 
        FROM AccountModule
        Action
        FROM ActionModule
        ChangeSet
        FROM ChangeSetModule;

Transaction ::= SEQUENCE {
    version         Version,
    date            UTCTime,
    value           Number,
    parent          Hash,
    -- the source account for the transaction
    sourceAccount   Hash,
    -- the target account for the transaction
    targetAccount   Hash,
    actions         SEQUENCE OF Action
}

SignedTransaction ::= SEQUENCE {
    version         Version,
    transaction     Transaction,
    transactionHash Hash,
    signature       Signature
}

TransactionTrace ::= SEQUENCE {
    traceHash       Hash,
    signature       Signature
}


LedgerEntry ::= SEQUENCE {
    version         Version,
    date            UTCTime,
    value           Number,
    transaction     Hash,
    -- the source account for the transaction
    account         Hash
}


TransactionMessage ::= SEQUENCE {
    version             Version,
    -- transaction header information
    sourceAccount       Hash,
    targetAccount       Hash,
    transactionHash     Hash,
    signature           Signature,
    -- transaction 
    signedTransaction   ANY,
    transactionTrace    SEQUENCE OF TransactionTrace,
    changeSet           SEQUENCE OF ChangeSet
}




END
