TransactionModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN
    IMPORTS Number, Hash, Version, Key
        FROM BasicModule
        Account 
        FROM AccountModule
        Action
        FROM ActionModule;

Transaction ::= SEQUENCE {
    version         Version,
    date            UTCTime,
    value           Number,
    parent          Hash,
    sourceAccount   Hash,
    targetAccount   Hash,
    actions         SEQUENCE OF Action
}

SignedTransaction ::= SEQUENCE {
    version         Version,
    id              Hash,
    transaction     Transaction,
    transactionHash Hash,
    signature       Key
}


END
